#!/usr/bin/env bash
# bootstrap-hermes-mcp.sh
# Installs and starts the HVE Hermes MCP Server as a user systemd service.
# No sudo required. Run as: bash ~/hermes-cfo/scripts/bootstrap-hermes-mcp.sh

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${HOME}/.hermes-mcp-venv"
SERVICE_SRC="${REPO_DIR}/dotfiles/hermes-mcp.service"
SERVICE_DEST="${HOME}/.config/systemd/user/hermes-mcp.service"
ENV_FILE="${HOME}/.hermes-mcp.env"
PORT=8765

echo "== HVE Hermes MCP Server Bootstrap =="

# ── 1. Python venv via uv ────────────────────────────────────────────────────
echo "→ Creating Python venv at ${VENV_DIR}"
uv venv "${VENV_DIR}" --python 3.12 --seed
uv pip install --python "${VENV_DIR}/bin/python" "mcp[cli]>=1.0"
echo "  venv ready."

# ── 2. Ensure log dirs exist ─────────────────────────────────────────────────
mkdir -p "${REPO_DIR}/logs/tasks"
[ -f "${REPO_DIR}/logs/tasks/tasks.json" ] || echo "[]" > "${REPO_DIR}/logs/tasks/tasks.json"
echo "  log dirs ready."

# ── 3. API key env file ──────────────────────────────────────────────────────
if [ ! -f "${ENV_FILE}" ]; then
    API_KEY="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
    cat > "${ENV_FILE}" <<ENVEOF
# HVE Hermes MCP Server — environment config
# Generated by bootstrap-hermes-mcp.sh — $(date -Iseconds)

HVE_MCP_API_KEY=${API_KEY}
HVE_MCP_PORT=8765

# Set this to your Tailscale Funnel public URL once Tailscale is configured:
# HVE_MCP_PUBLIC_URL=https://spark-5054.taile1234.ts.net
ENVEOF
    chmod 600 "${ENV_FILE}"
    echo "  API key generated and saved to ${ENV_FILE}"
    echo "  IMPORTANT: note your API key for the Copilot Studio connector."
    grep HVE_MCP_API_KEY "${ENV_FILE}"
else
    echo "  API key file already exists at ${ENV_FILE} — skipping generation."
fi

# ── 4. User systemd service (no sudo required) ───────────────────────────────
echo "→ Installing user systemd service"
mkdir -p "${HOME}/.config/systemd/user"
cp "${SERVICE_SRC}" "${SERVICE_DEST}"
systemctl --user daemon-reload
systemctl --user enable hermes-mcp
systemctl --user restart hermes-mcp
echo "  service installed and started."

# ── 5. Smoke test ────────────────────────────────────────────────────────────
echo "→ Waiting for server to start..."
sleep 4
if curl -sf "http://127.0.0.1:${PORT}/.well-known/agent.json" > /dev/null; then
    echo "  PASS agent card reachable at http://127.0.0.1:${PORT}/.well-known/agent.json"
else
    echo "  WARN agent card not yet reachable — check: journalctl --user -u hermes-mcp -n 30"
fi

echo ""
echo "== Bootstrap complete =="
echo ""
echo "Service:    systemctl --user status hermes-mcp"
echo "Logs:       journalctl --user -u hermes-mcp -f"
echo "Local test: curl http://127.0.0.1:${PORT}/.well-known/agent.json"
echo ""
echo "== Next: Install Tailscale and expose publicly =="
echo ""
echo "  1. sudo apt-get install -y tailscale"
echo "  2. sudo tailscale up"
echo "  3. sudo tailscale funnel --bg ${PORT}"
echo "  4. tailscale funnel status   # note your public HTTPS URL"
echo "  5. Add HVE_MCP_PUBLIC_URL to ${ENV_FILE}"
echo "  6. systemctl --user restart hermes-mcp"
echo ""
echo "  Give the public URL + API key from ${ENV_FILE} to configure"
echo "  the Power Platform MCP connector in the HVE-Concierge-Agent-Dev environment."
